# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rj Bernaldo
email: rj.bernaldo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rjbernaldo.github.io" # the base hostname & protocol for your site
#twitter_username: rjbernaldo
github_username:  rjbernaldo

# Build settings
markdown: kramdown
